version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
  kibana:
      image: docker.elastic.co/kibana/kibana:8.15.3
      container_name: kibana
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - xpack.security.enabled=false

      ports:
        - "5601:5601"
      restart: always
      depends_on:
        - elasticsearch

volumes:
  es_data:
